openapi: 3.0.0
info:
  title: "Blog API"
  version: "1.0.0"
  description: "API documentation for managing blog posts."
paths:
  /api/posts:
    get:
      summary: "Get a list of posts"
      description: "Retrieve a list of blog posts with optional filtering and pagination."
      tags:
        - "Posts"
      parameters:
        - name: "author_id"
          in: "query"
          description: "Filter posts by author ID"
          required: false
          schema:
            type: "integer"
        - name: "title"
          in: "query"
          description: "Search posts by title"
          required: false
          schema:
            type: "string"
        - name: "page"
          in: "query"
          description: "Page number for pagination"
          required: false
          schema:
            type: "integer"
            default: 1
        - name: "per_page"
          in: "query"
          description: "Number of items per page (default: 15)"
          required: false
          schema:
            type: "integer"
            default: 15
      responses:
        200:
          description: "List of posts with pagination metadata."
          content:
            application/json:
              schema:
                type: "object"
                properties:
                  data:
                    type: "array"
                    items:
                      type: "object"
                      properties:
                        title:
                          type: "string"
                        author:
                          type: "string"
                        comments:
                          type: "array"
                          items:
                            type: "object"
                            properties:
                              text:
                                type: "string"
                              name:
                                type: "string"
                  meta:
                    type: "object"
                    properties:
                      current_page:
                        type: "integer"
                      last_page:
                        type: "integer"
                      per_page:
                        type: "integer"
                      total:
                        type: "integer"
        422:
          description: "Validation error for invalid parameters."
